export const communityType = {

    FeedList: "FeedList",
    MyFeedList: "MyFeedList",
    postLikesDislikes: "postLikesDislikes",
    postFollowUser: "postFollowUser",
    getReportList:"getReportList",
    postReportPost:"postReportPost",
    postSavePost:"postSavePost",
    deletePost:"deletePost",
    hidePost:"hidePost",
    unHidePost:"unHidePost",
    getFeedProfile:"getFeedProfile",
    getFollowerList:"getFollowerList",
    getFollowingList:"getFollowingList",
    postRemoveMyFollower:"postRemoveMyFollower",
    postaddPost:"postaddPost",
    postaddComment:"postaddComment",
    postgetComment:"postgetComment",
    sharedPost:"sharedPost",
    deleteSavedPost:"deleteSavedPost",
    MySavedPosts:"MySavedPosts",
    postDeleteComment:"postDeleteComment",
    postcommentsLike:"postcommentsLike",
    updatePost:"updatePost",
    getMyGroupsList:"getMyGroupsList",
    getAllGroupsList:"getAllGroupsList",
    getGroupsUserList:"getGroupsUserList",
    getGroupsPostList:"getGroupsPostList",
    getJoinGroups:"getJoinGroups",
    getGroupsDetails:"getGroupsDetails",
    ResetGroupsDetails:"ResetGroupsDetails",
    setMyFeedsData:"setMyFeedsData",

    setPublicFeedsData:"setPublicFeedsData",
    setSavedFeedsData:"setSavedFeedsData",
    setGroupFeedsData:"setGroupFeedsData",
    setCommentFeedsData:"setCommentFeedsData"
};

export const communityPath = {

    FeedList: "/farmer/feed",
    MyFeedList: "/farmer/feed",
    MySavedPosts:"/farmer/feed",
    postFollowUser: "/Feed/user/follow",
    getJoinGroups:"/group/join",
    ResetGroupsDetails:"",

    postLikesDislikes: "/Feed/addPostLikesDislikes",
    getReportList:"/Feed/GetReportList/",
    postReportPost:"/Feed/reportPost",
    postSavePost:"/Feed/savePost",
    deletePost:"/Feed/deletePost",
    hidePost:"/Feed/hidePost",
    unHidePost:"/Feed/unhidePost",
    getFeedProfile:"/Feed/getMyFollowerCount",
    getFollowerList:"/Feed/getMyFollowers",
    getFollowingList:"/Feed/getMyFollowings",
    postRemoveMyFollower:"/Feed/removeMyFollower",
    postaddPost:"/Feed/addPost",
    postaddComment:"/Feed/addComment",
    postgetComment:"/Feed/getComment",
    sharedPost:"/Feed/addShares",
    deleteSavedPost:"/Feed/deleteSavedPost",
    postDeleteComment:"/Feed/DeleteComment",
    postcommentsLike:"/Feed/addCommentsLikesDislikes",
    updatePost:"/Feed/updatePost",
    getMyGroupsList:"/group/getUserGroup",
    getAllGroupsList:"/group/getUserGroup",
    getGroupsUserList:"/group/getUsers/",
    getGroupsPostList:"/group/getGroupPost/",
    getGroupsDetails:"/group/get/"
}