import { UserManager } from '../storage';

export const Screen = {
  splash: 'splash',
  login: 'login',
  welcome: 'welcome',
  otpscreen: 'otpscreen',
  cropselection: 'cropselection',
  selectedCrop: 'selectedCrop',
  selectedCropDetail: 'selectedCropDetail',
  productDetails: 'productDetails',
  product: 'Buy Product',
  favouriteProduct: 'favouriteProduct',
  dashboard: 'dashboard',
  logout: 'logout',
  myAccount: 'myAccount',
  viewAllProduct: 'viewAllProduct',
  viewAllCategory: 'viewAllCategory',
  reviewProduct: 'reviewProduct',
  myCart: 'myCart',
  myServiceslist: 'myServiceslist',
  myPractice: 'myPractice',
  notification: 'notification',
  chatWithUs: 'chatWithUs',
  checkout: 'checkout',
  checkoutPayment: 'checkoutPayment',
  myOrderHistory: 'myOrderHistory',
  deliveryStatus: 'deliveryStatus',
  loyalityPoints: 'loyalityPoints',
  homes: 'Home',
  cropAdvisory: 'Crop Advisory',
  gromorStore: 'Gromor Store',
  marketValue: 'Market Value',
  welcomeHNI: 'welcomeHNI',
  payment: 'payment',
  language: 'language',
  addressDetails: 'addressDetails',
  viewAllDealers: 'viewAllDealers',
  viewAllReview: 'viewAllReview',
  testimonial: 'Testimonial',
  postFeed: 'Gromor Connect',
  createFeed: 'CreateFeed',
  similarProduct: 'SimilarProduct',
  FeedProfile: 'FeedProfile',
  Plantix: 'Plantix',
  dashboardHome: 'dashboardHome',
  dashboardCropAdv: 'dashboardCropAdv',
  dashboardProduct: 'dashboardProduct',
  dashboardStore: 'dashboardStore',
  dashboardMarket: 'dashboardMarket',
  chat: 'chat',
  adVideo: 'adVideo',
  checkoutNew: 'checkoutNew',
  shippingAddress: 'shippingAddress',
  ChangeStoreDetails: 'ChangeStoreDetails',
  bookingHistory: 'bookingHistory',
  changeStore: 'changeStore',
  bookingStatus: 'bookingStatus',
  GroupDetails: 'GroupDetails',
  PlantixSummary: 'PlantixSummary',
  PlantixSummaryDetails: 'PlantixSummaryDetails',
  PlantixRecommndation: 'PlantixRecommndation',
  FylloScreen: 'FylloScreen',
  myProfileScreen: 'myProfileScreen',
  myServices: 'myServices',
  myServicesDelivery: 'myServicesDelivery',
  SprayingServicsDetail: 'SprayingServicsDetail',
  serviceDetails: 'serviceDetails',
  cropDocktore:"Crop Droctor",
  Shop:'Shop',
  Community:'Community',
  Purchase:'Purchase'
  
};
