// import CropDetailScreen from '../pages/dashboard_modules/tabs/advisory-dashboard/CropDetailScreen';
// import QueryDetailScreen fro../pages/dashboard_modules/tabs/advisory-dashboard/PostQueryDetaileen';
import { UserManager } from '../storage';

export const Screen = {
  splash: 'splash',
  login: 'login',
  welcome: 'welcome',
  otpscreen: 'otpscreen',
  cropselection: 'cropselection',
  selectedCrop: 'selectedCrop',
  selectedCropDetail: 'selectedCropDetail',
  productDetails: 'productDetails',
  product: 'Buy Product',
  favouriteProduct: 'favouriteProduct',
  dashboard: 'dashboard',
  logout: 'logout',
  myAccount: 'MyAccount',
  viewAllProduct: 'viewAllProduct',
  viewAllCategory: 'viewAllCategory',
  viewAllCategoryData: "viewAllCategoryData",
  reviewProduct: 'reviewProduct',
  myCart: 'myCart',
  myServiceslist: 'myServiceslist',
  myPractice: 'myPractice',
  notification: 'notification',
  chatWithUs: 'chatWithUs',
  checkout: 'checkout',
  checkoutPayment: 'checkoutPayment',
  myOrderHistory: 'myOrderHistory',
  deliveryStatus: 'deliveryStatus',
  loyalityPoints: 'loyalityPoints',
  homes: 'Home',
  cropAdvisory: 'Crop Advisory',
  gromorStore: 'Gromor Store',
  marketValue: 'Market Value',
  welcomeHNI: 'welcomeHNI',
  payment: 'payment',
  language: 'language',
  newLanguage: 'newLanguage',
  addressDetails: 'addressDetails',
  viewAllDealers: 'viewAllDealers',
  viewAllReview: 'viewAllReview',
  testimonial: 'Testimonial',
  postFeed: 'Gromor Connect',
  createFeed: 'CreateFeed',
  similarProduct: 'SimilarProduct',
  FeedProfile: 'FeedProfile',
  Plantix: 'Plantix',
  dashboardHome: 'dashboardHome',
  dashboardCropAdv: 'dashboardCropAdv',
  dashboardProduct: 'dashboardProduct',
  dashboardStore: 'dashboardStore',
  dashboardMarket: 'dashboardMarket',
  chat: 'chat',
  adVideo: 'adVideo',
  checkoutNew: 'checkoutNew',
  shippingAddress: 'shippingAddress',
  ChangeStoreDetails: 'ChangeStoreDetails',
  bookingHistory: 'bookingHistory',
  changeStore: 'changeStore',
  bookingStatus: 'bookingStatus',
  GroupDetails: 'GroupDetails',
  PlantixSummary: 'PlantixSummary',
  PlantixSummaryDetails: 'PlantixSummaryDetails',
  PlantixRecommndation: 'PlantixRecommndation',
  FylloScreen: 'FylloScreen',
  myProfileScreen: 'myProfileScreen',
  myServices: 'myServices',
  myServicesDelivery: 'myServicesDelivery',
  SprayingServicsDetail: 'SprayingServicsDetail',
  serviceDetails: 'serviceDetails',
  cropDocktore: "Crop Droctor",
  Shop: 'Shop',
  Community: 'Community',
  Purchase: 'Purchase',
  MyServicesScreen: 'MyServicesScreen',
  DoorDelivery: 'DoorDeliveryComponent',
  SprayingService: 'SprayingServiceDetail',
  MyBooking: "MyBooking",
  MyAccount: "MyAccount",
  newServiceRequest: 'NewServiceRequestScreen',
  SuccessScreen: 'SuccessScreen',
  WeatherScreen: 'WeatherScreen',
  NextDays: 'NextDaysScreen',
  MyOrder: "MyOrder",
  PurchaseDetail: "PurchaseDetail",
  BookingDetails: "BookingDetails",
  PostDetail:"PostDetail",
Notification: "notification",
NewPost:"newPost",
Profile:"profile",
ReportModal:"ReportModal",
CropDetailScreen: "CropDetailScreen",
QueriesScreen:"QueriesScreen",
PostQueryDetail:"PostQueryDetail",
NewQueryScreen:"NewQueryScreen",
NewVideoQueryScreen:"NewVideoQueryScreen",
CropDoctorScreen:"CropDoctorScreen",
};
