export const ProductType = {
  similarProducts: 'similarProducts',
  similarProductsByStoreCode: 'similarProductsByStoreCode',
  productDetail: 'productDetail',
  productCategory: 'productCategory',
  productBanners: 'productBanners',
  allProducts: 'allProducts',
  productByCategory: 'productByCategory',
  productReviewIndividual: 'productReviewIndividual',
  testimonialIndividual: 'testimonialIndividual',
  productCart: 'productCart',
  addFavProduct: 'addFavProduct',
  favProductByFarmerId: 'favProductByFarmerId',
  productReview: 'productReview',
  myCart: 'myCart',
  deleteCartProduct: 'deleteCartProduct',
  deleteFavProduct: 'deleteFavProduct',
  NotifyMe: 'notifyMe',
  dealerAddressByLoc: 'dealerAddressByLoc',
  allDealersAddress: 'allDealersAddress',
  productByStoreCode: 'productByStoreCode',
  productByStoreCode_type: 'productByStoreCode_type',
  categoryProductByStore: 'categoryProductByStore',
  categoryProductFilters: 'categoryProductFilters',
  video: 'advertisements',
  checkReview: 'checkReview',
  bookNow: 'bookNow',
  bookNowFromcartAction: 'bookNowFromcartAction',
  rewardPoints: 'rewardPoints',
  bookingHistory: 'bookingHistory',
  getFilterStatus: 'getFilterStatus',
  productCartBooking: 'productCartBooking',
  MyCartBooking: 'MyCartBooking',
  productSubCategory: 'productSubCategory',
  deleteCartBookingProduct: 'deleteCartBookingProduct',
  bookingShipmentDetails: 'bookingShipmentDetails',
 
  //Old_API's - Callmethod>>>>
  newProduct: 'newlyLaunched',
  popularProduct: 'popularProduct',
  favProduct: 'favProduct',
  productBySearch: 'productBySearch',
  shippingAddressById: 'shippingAddressById',
  shippingAddressByFarmer: 'shippingAddressByFarmer',
  shippingAddress: 'shippingAddress',
  updateShippingAddress: 'updateShippingAddress',
  deleteShippingAddress: 'deleteShippingAddress',
  productStockAvailibility: 'productStockAvailibility',
  uploadMedia: 'uploadMedia',
  searchProduct: 'searchProduct',
  dealerAddressByDistrict: 'dealerAddressByDistrict',
  //Old_API's - Callmethod>>>>
};

export const ProductAPIPath = {
  similarProducts: '/product/similarProducts',
  similarProductsByStoreCode: '/product/similar-products-by-category-storecode',
  productDetail: '/product',
  productCategory: '/category/all',
  productSubCategory: '/category/all/subCategory',
  productBanners: '/product/banners',
  allProducts: '/product/all',
  productByCategory: '/product/byCategory',
  productReviewIndividual: '/product/review-by-id',
  testimonialIndividual: '/testimonial/by',
  productCart: '/product/cart',
  addFavProduct: '/product/favouriteProducts',
  favProductByFarmerId: '/product/favouriteProducts/farmer',
  productReview: '/product/review',
  myCart: '/product/cart-details-by',
  deleteCartProduct: '/product/cart',
  NotifyMe: '/product/notify-item',
  dealerAddressByLoc: '/dealers-address/dealers-address-by-latitude-longitude',
  productByStoreCode: '/product/by-storecode',
  productByStoreCode_type: '/product/by-storecode-type',
  video: '/product/advertisements',
  allDealersAddress: '/dealers-address/dealers-address',
  categoryProductByStore: '/product/by-category-storecode',
  categoryProductFilters: '/product/product-list',
  checkReview: '/product/has-product-purchased',
  bookNow: '/track-booking',
  bookingHistory: '/track-booking/farmer',
  rewardPoints: '/reward/reward-points',
  getFilterStatus: '/orders/status',
  productCartBooking: '/track-booking/cart',
  MyCartBooking: '/track-booking/cart/user',
  deleteCartBookingProduct: '/track-booking/cart',
  bookNowFromcartAction: '/track-booking/cart2order',
  bookingShipmentDetails: '/track-booking',
  
  //Old_API's - Callmethod>>>>
  newProduct: '/product/featured',
  popularProduct: '/product/bestSeller',
  favProduct: '/product/all/favouriteProducts',
  productBySearch: '/product/search',
  shippingAddressById: '/shipping-address/by',
  shippingAddressByFarmer: '/shipping-address/by-farmer',
  shippingAddress: '/shipping-address',
  updateShippingAddress: '/shipping-address/change-selected',
  productStockAvailibility: 'product/item/instock',
  uploadMedia: '/product/upload/media',
  searchProduct: '/product/globalsearch',
  dealerAddressByDistrict: '/dealers-address/dealers-address-by-district',
  //Old_API's - Callmethod>>>>
};
